### ISSUE TITLE
Missing link to GitHub repo

### ISSUE THREAD

**Issue by szabgab** [yuki-kimoto/SPVM-Sys#2]
Most CPAN packages include a link to their GitHub repository to make it easy to find the official source code. It would be nice if you could also include those links. I've written a blog post explaining how: https://perlmaven.com/how-to-add-link-to-version-control-system-of-a-cpan-distributions

**Comment by yuki-kimoto** [comment]
Thanks. 

Could you pull reqeust to add the repository link?

Or do I do it?

**Comment by szabgab** [comment]
Sure. I've sent you a PR. I'd appreciate if you approved it for Hacktoberfest as well.

**Comment by yuki-kimoto** [comment]
Thanks. I merged it now.
